### ISSUE TITLE
Kafka Stream Query to fetch song details where song id  > 10

### ISSUE THREAD

**Issue by bhagyashri10** [confluentinc/kafka-streams-examples#101]
How can I write a interactive query using kafka stream to fetch song details where song id is greater than 10?

I am using **KafkaMusicExample** of confluentinc:

https://github.com/confluentinc/kafka-streams-examples/blob/4.0.0-post/src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/KafkaMusicExample.java

**Comment by OneCricketeer** [comment]
You can filter what gets added to the ArrayList based on the songId values in here

https://github.com/confluentinc/kafka-streams-examples/blob/a841b39b772ace5ca0cbe50fc767333ce2bedaa4/src/main/java/io/confluent/examples/streams/interactivequeries/kafkamusic/MusicPlaysRestService.java#L148-L157
