### ISSUE TITLE
Microservices example fails when build against upcoming AK 2.0

### ISSUE THREAD

**Issue by miguno** [confluentinc/kafka-streams-examples#112]
I created a test branch to showcase the problem: https://github.com/confluentinc/kafka-streams-examples/tree/master-KIP270-Orders-Example.  (The relevant commit is https://github.com/confluentinc/kafka-streams-examples/commit/d7a36aae6dd2a53b5c5d6920e5adadd647cb2104.) This test branch is based upon the PR branch we use for adding Scala API examples (for upcoming AK 2.0) to this repo, see https://github.com/confluentinc/kafka-streams-examples/pull/109.

Build error:

```
Tests in error:
  EndToEndTest.shouldCreateNewOrderAndGetBackValidatedOrder:61 » NotFound HTTP 4...
  EndToEndTest.shouldProcessManyInvalidOrdersEndToEnd:122 » NotFound HTTP 404 No...
  EndToEndTest.shouldProcessManyValidOrdersEndToEnd:87 » NotFound HTTP 404 Not F...
  OrdersServiceTest.shouldGetOrderByIdWhenOnDifferentHost:182 » NotFound HTTP 40...
  OrdersServiceTest.shouldGetValidatedOrderOnRequest:131 » NotFound HTTP 404 Not...
  OrdersServiceTest.shouldPostOrderAndGetItBack:86 » NotFound HTTP 404 Not Found
```

@benstopford Could you take a look at the test failures above?  I don't have the time unfortunately to finish https://github.com/confluentinc/kafka-streams-examples/pull/109 and to also fix/update the microservices example.

**Comment by benstopford** [comment]
This was fixed as above
