### ISSUE TITLE
Make a state store with AVRO

### ISSUE THREAD

**Issue by dahuchao** [confluentinc/kafka-streams-examples#125]
In that post : 
https://stackoverflow.com/a/50752095/9234107

_you might be able to use a "global store" instead of a GlobalKTable. For this case, you can provide a custom Processor that can implement a filter before you populate the global store._

I try to make a store like this : 

```java
StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
		Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
		Serdes.serdeFrom(CustomerAvro.class));
```
But a got that error : 

Caused by: java.lang.IllegalArgumentException: Unknown class for built-in serializer. Supported types are: String, Short, Integer, Long, Float, Double, ByteArray, ByteBuffer, Bytes

How can I make a store with Avro objects ?

**Comment by mjsax** [comment]
Confluent Open Source ships with Avro Serdes already. No need to create them via `Serdes.serdeFrom()`: https://docs.confluent.io/current/streams/developer-guide/datatypes.html#avro

**Comment by dahuchao** [comment]
That's what i tried : `Serdes.serdeFrom(CustomerAvro.class)` see : 

```java
StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
		Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
		Serdes.serdeFrom(CustomerAvro.class));
```

Seeing the documentation, i tried like this : 

```java
Serde<CustomerAvro> serdeCustomer = new SpecificAvroSerde<>();
StoreBuilder<KeyValueStore<String, CustomerAvro>> personStoreSupplier = Stores.keyValueStoreBuilder(
		Stores.persistentKeyValueStore("personProcessStore"), Serdes.String(),
		Serdes.serdeFrom(serdeCustomer.serializer(), serdeCustomer.deserializer()));
```

It works !
Thank's a lot for your support.

**Comment by dahuchao** [comment]
The problem comes again see : https://github.com/confluentinc/kafka-streams-examples/issues/126
