### ISSUE TITLE
Time window 24 hour

### ISSUE THREAD

**Issue by margitbomholt** [confluentinc/kafka-streams-examples#141]
I have a problem , I want to aggregate in a 24 hour time window in a Kafka Streams application, it works ok, except that the aggregation intevale becomes 02-02 instead of 24-24 (midnight to midnight). 

Is there any settings about the timezone in the Kafka Streams api? the server is running whith the following datetime settings:

  Local time: tor 2018-08-09 08:29:55 CEST
  Universal time: tor 2018-08-09 06:29:55 UTC
  RTC time: tor 2018-08-09 06:29:55
  Time zone: Europe/Copenhagen (CEST, +0200)
Network time on: yes
NTP synchronized: yes
RTC in local TZ: no

Any hints or help will be appreciated

**Comment by ESLHemantSangle** [comment]
@margitbomholt you got any hint about this as i am also facing the same issue

**Comment by satansk** [comment]
faced with the same problem :(

**Comment by ESLHemantSangle** [comment]
@mjsax sir can you help me on this https://stackoverflow.com/questions/54395471/how-to-handle-different-timezone-in-kafka-streaming

**Comment by mjsax** [comment]
@ESLHemantSangle I replied to the SO question and the answer was accepted. Thus I am closing this ticket. Feel free to reopen if you have follow up questions.

I also create a ticket to track the feature request: https://issues.apache.org/jira/browse/KAFKA-7911

Furthermore, I copy my answer from SO below, too:

You can "shift" the timestamps using a custom `TimestampExtractor` -- before you write the result back into the output topic, you can use a `Transformer` and "shift" the timestamps back via `context.forward(key, value, To.all().withTimestamps())`.
