### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by nimo1981** [confluentinc/kafka-streams-examples#147]
The following imports are missing

import io.confluent.examples.streams.avro.microservices.Order;
import io.confluent.examples.streams.avro.microservices.OrderState;

**Comment by bbejeck** [comment]
Thanks for reporting @nimo1981. Can you say which branch you are one and which file(s) are missing the imports?

**Comment by wuyongdec** [comment]
The following imports are missing
import io.confluent.examples.streams.avro.*
some packages about arro are missing in current main branch

**Comment by donaldyht** [comment]
how to find these imports????

**Comment by mjsax** [comment]
Avro Serdes are shipped with schema registry: https://github.com/confluentinc/schema-registry

For `io.confluent.examples.streams.avro.microservices.Order` and ` io.confluent.examples.streams.avro.microservices.OrderState` see: https://github.com/confluentinc/kafka-streams-examples#using-intellij-or-eclipse

**Comment by mjsax** [comment]
@nimo1981 Can we resolve this issue?

**Comment by superbigdata** [comment]
> @nimo1981 Can we resolve this issue?

I have the same problem when import io.confluent.examples.streams.avro.* (The path is 
 io/confluent/examples/streams/GlobalKTablesExample.java),
such as 
import io.confluent.examples.streams.avro.Customer;
import io.confluent.examples.streams.avro.EnrichedOrder;
import io.confluent.examples.streams.avro.Order;
import io.confluent.examples.streams.avro.Product;
where can I find them?

**Comment by superbigdata** [comment]
> @superbigdata See instructions in the README: https://github.com/confluentinc/kafka-streams-examples#using-intellij-or-eclipse
> 
> Those classes are generated during the build.

I found it. Thank you very much

**Comment by revurirams123** [comment]
> > @superbigdata See instructions in the README: https://github.com/confluentinc/kafka-streams-examples#using-intellij-or-eclipse
> > Those classes are generated during the build.
> 
> I found it. Thank you very much

Hi, 
I am also facing same problem inspite of following the instructions, wondering  wha I am missing, it is not generating missing classes for me in eclipse even after running "pom.xml file and choose Run As > Maven generate-sources" and mvn -Dskip.tests=true compile as well, can you please help if I have to do anything else. i built all other dependent projects successfully as mentioned requirements section.
