### ISSUE TITLE
Microservices: ValidationsAggregatorService.java failure (DEVX-244)

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-streams-examples#150]
https://github.com/confluentinc/kafka-streams-examples/blob/5.0.x/src/main/java/io/confluent/examples/streams/microservices/ValidationsAggregatorService.java#L41-L54

Problem: fails for the same reason that `EmailService` failed (and was fixed in PR #148, #138)

Serdes must be initialised with the schema registry but are being cached in a static Joined variable before the schema registry is configured.

**Comment by mjsax** [comment]
Closing. PR was merged.
