### ISSUE TITLE
Kafka Externalization of Secrets and Kafka Connect REST API

### ISSUE THREAD

**Issue by ksbalan2018** [confluentinc/kafka-streams-examples#158]
Hi,
Externalization of secrets is a nice feature addition to Kafka. That said, this should not be triggered when querying for connector status or task status within Kafka connect.
i ran the following command
curl -X GET http://hostname:port/connectors/connectorname/status
and  i noticed queries related to configuration. 

Querying for externalized provider makes sense if we are querying for config

**Comment by cricket007** [comment]
Same for #159 

If you have a problem specific to Kafka Connect, please file a JIRA. However, this is actively being fixed - https://issues.apache.org/jira/browse/KAFKA-5117?focusedCommentId=16737143&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16737143

**Comment by mjsax** [comment]
Please file a Jira at https://issues.apache.org/jira/projects/KAFKA
