### ISSUE TITLE
Kafka Connect distributed and Connector failures

### ISSUE THREAD

**Issue by satyaelite** [confluentinc/kafka-streams-examples#159]
I see there are many drawbacks in the way connectors are run within the distributed connect framework some of which have already been mentioned in KIP 304. That said, there needs to be additional control within a connector to be able to
1. exit upon certain conditions (unload itself from the worker) - currently the only workaround is to use REST API 
2. produce connector specific log files
3. command line interface for workers to launch (similar to how it works for standalone mode) without the need for REST interfaces.

**Comment by cricket007** [comment]
This repo is for Kafka Streams, not Kafka Connect... Am I missing something?

**Comment by mjsax** [comment]
Please file a ticket for Apache Kafka: https://issues.apache.org/jira/projects/KAFKA/issues
