### ISSUE TITLE
help ,i cant find the example code ablout "Querying local custom state stores" with java

### ISSUE THREAD

**Issue by fulndon** [confluentinc/kafka-streams-examples#162]
is it not have example?

**Comment by mjsax** [comment]
Check out the `KafkaMusic` example: https://github.com/confluentinc/kafka-streams-examples/tree/5.0.0-post/src/main/java/io/confluent/examples/streams/interactivequeries

Also check out the docs: https://docs.confluent.io/current/streams/developer-guide/interactive-queries.html

**Comment by fulndon** [comment]
body,i also saw that ,If the code is not changed, it cannot run 
so i want those code like [that](https://github.com/confluentinc/kafka-streams-examples/blob/5.0.0-post/src/main/java/io/confluent/examples/streams/interactivequeries/WordCountInteractiveQueriesExample.java) about Querying local custom state stores
