### ISSUE TITLE
missing import 

### ISSUE THREAD

**Issue by tanzanlong** [confluentinc/kafka-streams-examples#170]
The following imports are missing ：

import io.confluent.examples.streams.avro.PlayEvent

**Comment by meysamabl** [comment]
The "avro" directory is missing from the source code. I am also getting the same error. 
Thanks

**Comment by guozhangwang** [comment]
@meysamabl could you share your java, scala and gradle versions in your environment, and the exact cmd you tried?

**Comment by meysamabl** [comment]
I am using java 1.8 and intelij IDE. I am getting compiler error for all imports from avro package. There is no avro package in the repository. You can check it yourself.

Thanks,

**Comment by mjsax** [comment]
Did you run `mvn package` on command line? `PlayEvent` will be generated than. Unfortunately, IntelliJ is not smart enough to run this automatically for your and thus when you clone the repo and import it, the class is missing initially.

**Comment by mjsax** [comment]
I guess, we should update the README...

**Comment by mjsax** [comment]
Added a PR: https://github.com/confluentinc/kafka-streams-examples/pull/177

**Comment by meysamabl** [comment]
Thank you. `mvn package` generated the missing import.
