### ISSUE TITLE
KafkaStreams : start method too long

### ISSUE THREAD

**Issue by dahuchao** [confluentinc/kafka-streams-examples#180]
Hello,
I've got a problem with the method

> org.apache.kafka.streams.KafkaStreams.start()

because it makes so much time to respond that my service goes down.

The service is a spring service like this : 

```java
	@PostConstruct
	private void init() throws InterruptedException {
		configurer();
		StreamsBuilder builder = new StreamsBuilder();
		builder.globalTable(kafkaTopic, Materialized.as("customerStore"));
		Topology topology = builder.build();
		KafkaStreams streams = new KafkaStreams(topology, props);
		streams.start();
		customerStore = waitUntilStoreIsQueryable("customerStore", streams);
		Runtime.getRuntime()
				.addShutdownHook(new Thread(streams::close));
	}
```
This is the configurer() method : 

```java
	protected void configurer() {
		try (InputStream input = this.getClass()
				.getClassLoader()
				.getResourceAsStream(kafkaProperties)) {
			journal.debug("Chargement de la conf. {}", kafkaProperties);
			props.load(input);
			props.put(StreamsConfig.APPLICATION_ID_CONFIG, kafkaAppid);
			props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, StringSerde.class);
			props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, SpecificAvroSerde.class);
			props.put(StreamsConfig.DEFAULT_DESERIALIZATION_EXCEPTION_HANDLER_CLASS_CONFIG,
					LogAndContinueExceptionHandler.class);
		} catch (IOException ex) {
			journal.debug(ex.getMessage());
		}
	}
```

This is the waitUntilStoreIsQueryable method : 

```java
	public ReadOnlyKeyValueStore<K, V> waitUntilStoreIsQueryable(final String storeName, final KafkaStreams streams)
			throws InterruptedException {
		journal.info("Attente store {} ...", storeName);
		ReadOnlyKeyValueStore<K, V> store;
		while (true) {
			try {
				store = streams.store(storeName, QueryableStoreTypes.<K, V>keyValueStore());
				break;
			} catch (InvalidStateStoreException ignored) {
				// store not yet ready for querying
				Thread.sleep(500);
			}
		}
		journal.info("Store {} operationnel.", storeName);
		return store;
	}
```
What can explain that problem ?
Thanks for your help

**Comment by Protoss78** [comment]
Hi,

We had a similar issue. I think your problem is related to this already reported bug here: https://issues.apache.org/jira/browse/KAFKA-7380

According to the documentation the start method should be non-blocking. But this is not the case when a  global store is used.

**Comment by dahuchao** [comment]
En mode DEBUG, voici les traces obtenues : 

```
16:49:28.058 INFO  f.l.b.e.customer.CustomerService - Lecture du referentiel des clients (customer) : start...
16:49:28.059 DEBUG o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_customer-89065bc3-1f64-457f-ae04-a250ba8658b7]Starting Streams client
16:49:28.064 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]State transition from RUNNING to REBALANCING
16:49:31.259 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]State transition from REBALANCING to RUNNING
16:51:29.460 DEBUG o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]Stopping Streams client with timeoutMillis = 0 ms.
16:51:29.462 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]State transition from RUNNING to PENDING_SHUTDOWN
16:51:29.493 DEBUG o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_merchant-9a381a25-26e9-4129-ba10-74d1a2408209]Stopping Streams client with timeoutMillis = 0 ms.
16:51:29.493 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_merchant-9a381a25-26e9-4129-ba10-74d1a2408209]State transition from RUNNING to PENDING_SHUTDOWN
16:51:29.600 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_merchant-9a381a25-26e9-4129-ba10-74d1a2408209]State transition from PENDING_SHUTDOWN to NOT_RUNNING
16:51:29.628 INFO o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_merchant-9a381a25-26e9-4129-ba10-74d1a2408209]Streams client stopped completely
```

**Comment by mjsax** [comment]
KAFKA-7380 seems to be related, however, if should only be an issue for the very first time you start the service. For a stopped service that is restarted on the same machine, the global table should be stored on disk and thus does not need to be loaded from Kafka.

However, if load the state is really the issue, that fixing KAFKA-7380 would not help for this case directly, because you call `waitUntilStoreIsQueryable("customerStore", streams);` -- this call would also block until the store is ready.

About the logs:
```
16:49:31.259 INFO  o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]State transition from REBALANCING to RUNNING
16:51:29.460 DEBUG o.apache.kafka.streams.KafkaStreams - stream-client [sc_acc_u0_mdLegalPersonLatestValues-fb4aed3c-b1ac-429d-869b-ff94ad61d550]Stopping Streams client with timeoutMillis = 0 ms.
```
Seems like you call `close()` after about 60 seconds -- how is this `close()` call triggered?

**Comment by mjsax** [comment]
I don't think you can do much about KAFKA-7380...

However, if PAAS sends a SIGTERM and that calls the shutdown hook, you should increase the startup timeout. I am not familiar with OpenShift PAAS, but I am sure that you can configure the timeout accordingly.

**Comment by dahuchao** [comment]
We resolved that problem by configuring the timeout but we now want to optimize the scalability of our system.
To realise the scalability the PAAS mount another POD. The time take by the application to boot in that new pod is too long because of recreating the store, cash for the customers.

One solution would be to accumulate the datas in our SGBD but i consider it's less robustness. I would prefer stay in kafka environnement.

Our pods dont have any persistent volume. If we change our configuration to give pods (of the same kafka group) a persistant volume, do you think we could optimize startup ?
If we were in a simple pod architecture, i am sure that local rocksdb files would accelerate the startup. But i dont really understand how it works in a multi-pod (same PV) configuration, too instances of the same application would access (and write) new incomming customer message in the same rockdb.
Thanks for you help
