### ISSUE TITLE
where is the io.confluent.examples.streams package? Is it from parent?

### ISSUE THREAD

**Issue by rroyhere** [confluentinc/kafka-streams-examples#182]
where is the acro package under io.confluent.examples.streams in the example 
https://github.com/confluentinc/kafka-streams-examples/tree/5.0.0-post? I am not finding the Product, PlayEvent, Song etc classes, microservices packages mentioned in the io.confluent.examples.streams.avro package for this project.
Is it from parent rest util? Sorry, I am since I am working from restricted env, can download from all the repos, so cant see if present in parent proj

**Comment by kugaudo** [comment]
I had the same problem.
Just switch to the latest stable release (v5.0.0 for now):

`git checkout tags/v5.0.0 -b v5.0.0`

**Comment by rroyhere** [comment]
Please ignore this question, when I fully built it outside restricted environment, I am able to get them. They are generated sources for schemas. Thanks
