### ISSUE TITLE
connector instance update via Kafka rest not affect

### ISSUE THREAD

**Issue by tieungao88** [confluentinc/kafka-streams-examples#183]
Hi all,
I have problem about update "connector instance" via kafka-rest:
The first config:
![image](https://user-images.githubusercontent.com/6977423/48176785-4cc41400-e344-11e8-832a-b02cebe708aa.png)

Update config:
![image](https://user-images.githubusercontent.com/6977423/48176810-69f8e280-e344-11e8-86e0-29e39d060db1.png)

But I don't  find new topic for new table.whitelist=INTEGATION_SERVICES.SETTING.

How to resolve it?

Thanks

**Comment by cricket007** [comment]
This repo is for Kafka Streams, not Kafka Connect... Am I missing something?

**Comment by mjsax** [comment]
Please file a JIRA at https://issues.apache.org/jira/projects/KAFKA
