### ISSUE TITLE
Microservices example: Migrating the microservices example to KSQL

### ISSUE THREAD

**Issue by pablocastilla** [confluentinc/kafka-streams-examples#186]
Hi!

I am trying to implement your logic in .net and as I can not use kafka streams I have a lot of doubts. I think it would be very interesting if you create a new microservices example without using any java streaming, just KSQL. It could be a good reference to people that doesn't use JVM in their microservices.

Thanks

**Comment by cricket007** [comment]
Perhaps this would be better tracked over at https://github.com/confluentinc/ksql/issues since this repo is dedicated to Kafka Streams examples?

**Comment by pablocastilla** [comment]
Hi!

Thanks for answering.

Well, I think it is impossible to do in ksql:
https://github.com/pablocastilla/kafkiano/blob/master/README.md

Thanks

**Comment by cricket007** [comment]
KSQL provides a REST API for all clients that are non JVM to use. But, again, that's a discussion for there not here, I would say

**Comment by mjsax** [comment]
Please file a JIRA at https://github.com/confluentinc/ksql
