### ISSUE TITLE
I encountered an error when using KSQL's webUI

### ISSUE THREAD

**Issue by superbigdata** [confluentinc/kafka-streams-examples#188]
when i use 'show tables;' the results are normal.
![_20190107173031](https://user-images.githubusercontent.com/38806221/50760167-fcb0f180-12a1-11e9-9786-db15e3ca78b3.png)
but when i use 'SELECT * FROM USERS ;'  Error encountered.
![_20190107173301](https://user-images.githubusercontent.com/38806221/50760328-72b55880-12a2-11e9-945a-f791bf0be1ac.png)
What's wrong with that?
Thank you in advance for your help

**Comment by cricket007** [comment]
KSQL doesn't appear to be an issue with this repo? Am I missing something?

**Comment by mjsax** [comment]
Please open a ticket at https://github.com/confluentinc/ksql
