### ISSUE TITLE
Consumed class has moved to org.apache.kafka.streams.kstream.Consumed

### ISSUE THREAD

**Issue by avrono** [confluentinc/kafka-streams-examples#192]
In your pageViewTypedDemo.java the Consumed class has an incorrect import and seems to have moved to org.apache.kafka.streams.kstream.Consumed in kafka-streams 2.1

**Comment by mjsax** [comment]
`PageViewTypedDemo.java` is part of the Apache Kafka project. If there are any issues, please file a ticket for Kafka: https://issues.apache.org/jira/projects/KAFKA/issues
