### ISSUE TITLE
Failed to build schema-registry

### ISSUE THREAD

**Issue by vinayprabhu81** [confluentinc/kafka-streams-examples#218]
I get this error while trying to build schema-registry:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project kafka-schema-registry: Compilation failure: Compilation failure:
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[122,31] cannot find symbol
[ERROR] symbol: class ProtocolMetadata
[ERROR] location: class org.apache.kafka.common.requests.JoinGroupRequest
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[43,7] io.confluent.kafka.schemaregistry.masterelector.kafka.SchemaRegistryCoordinator is not abstract and does not override abstract method performAssignment(java.lang.String,java.lang.String,java.util.List<org.apache.kafka.common.message.JoinGroupResponseData.JoinGroupResponseMember>) in org.apache.kafka.clients.consumer.internals.AbstractCoordinator
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[122,50] metadata() in io.confluent.kafka.schemaregistry.masterelector.kafka.SchemaRegistryCoordinator cannot override metadata() in org.apache.kafka.clients.consumer.internals.AbstractCoordinator
[ERROR] return type java.util.List is not compatible with org.apache.kafka.common.message.JoinGroupRequestData.JoinGroupRequestProtocolSet
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[121,3] method does not override or implement a method from a supertype
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[125,29] cannot find symbol
[ERROR] symbol: class ProtocolMetadata
[ERROR] location: class org.apache.kafka.common.requests.JoinGroupRequest
[ERROR] /Users/Vinay/Desktop/Kafka/schema-registry/core/src/main/java/io/confluent/kafka/schemaregistry/masterelector/kafka/SchemaRegistryCoordinator.java:[140,3] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project kafka-schema-registry: Compilation failure

**Comment by mjsax** [comment]
You should open an ticket against https://github.com/confluentinc/schema-registry
