### ISSUE TITLE
Kafka Streams Listing and Trying describe topics not part of the topology

### ISSUE THREAD

**Issue by santanu33** [confluentinc/kafka-streams-examples#220]
we have a simple Kafka Stream filtering application which is working perfectly except one thing.

The stream application trying to describe every topic in the cluster. After googling the most relevant thread I have found is https://stackoverflow.com/questions/54599482/kafka-streams-listing-and-trying-describe-topics-not-part-of-the-topology

**Comment by mjsax** [comment]
What is your question?

**Comment by ArsenGasparyan** [comment]
I also have the same problem.
I have ACLs on some topics and they are not included in Kafka streams topology.
But when I am running my Kafka stream app it wants to describe those topics also and I have a bunch of errors in a log file.
So I want to know how I can fix it?

**Comment by mjsax** [comment]
Unfortunately, you cannot do much. It's a know issue and we actually plan to address it in AK 2.5 release (https://issues.apache.org/jira/browse/KAFKA-7317).

For now, you need to set ACL as described in the docs: https://docs.confluent.io/current/streams/developer-guide/security.html#required-acl-setting-for-secure-ak-clusters
