### ISSUE TITLE
addGlobalStore examples are not present

### ISSUE THREAD

**Issue by hashhar** [confluentinc/kafka-streams-examples#251]
Currently the Processor API equivalent of a GlobalKTable (ie. `builder.addGlobalStore`) is not documented well enough and how does it work.

Some examples for this would be much appreciated.

**Comment by hashhar** [comment]
Never mind. It was quite simple actually but maybe the documentation can clarify a bit.

Here's my understanding.

Global State Stores use the `inputTopic` itself as the changelog topic. ie. When an application is started all records in the topic are loaded as it is into the state store using a separate thread.

Once the changelog has been consumed any new records on the `inputTopic` are passed to the `Processor` instance returned by the `ProcessorSupplier` passed during the call to `addGlobalStore()`. YOU MUST ONLY DO `stateStore.put(key, value)` or `stateStore.delete(key)` depending on if the record is a tombstone or not.

**Comment by ableegoldman** [comment]
@hashhar https://github.com/apache/kafka/pull/6803 😄
