### ISSUE TITLE
Encapsulate EmbeddedSingleNodeKafkaCluster in a seperately-available maven/gradle/sbt dep

### ISSUE THREAD

**Issue by peoplemerge** [confluentinc/kafka-streams-examples#26]
As discussed in this thread https://groups.google.com/forum/#!topic/confluent-platform/_pJ1g9g1woY

It would be great if I could just include EmbeddedSingleNodeKafkaCluster and it's deps in test scope to easily run integration tests.  It seems like right now there is a lot of cut & paste programming happening out there.

**Comment by ryan-barker-zefr** [comment]
This is a really big deficiency for our team. Not having an artifact to make testing easier seems like a big deal to me.

Is the current acceptable use to copy and paste?

**Comment by guozhangwang** [comment]
We are indeed working on getting a core-test-utils artifact which will include some mocked broker module for users to write integration tests easier. That is on our ongoing roadmap.

For now please bare with us and use the copy-paste approach.

**Comment by cricket007** [comment]
Is there a JIRA to watch for this? I notice that at least `connect` and `streams` have the a similar `EmbeddedKafkaBroker` class in their unit tests.

**Comment by mjsax** [comment]
There is
 - https://issues.apache.org/jira/browse/KAFKA-5041
 - https://issues.apache.org/jira/browse/KAFKA-7852

**Comment by cricket007** [comment]
Thanks!

In the meantime, we've been using a combination of the testcontainers or junit-kafka projects

**Comment by ryan-barker-zefr** [comment]
We have made some progress on our side. We are looking into making an open source version of this but honestly we'd prefer to provide the code that we have done and have confluent maintain it.

**Comment by cricket007** [comment]
The embedded cluster would be mantained in the Apache Kafka repo, not just by Confluent.

**Comment by LeonardoBonacci** [comment]
Any progress on this issue?

**Comment by LeonardoBonacci** [comment]
Hi all, until there is an agreement on who will maintain these three classes - this issue dates from 2017... - you can use [this modernized fork](https://github.com/LeonardoBonacci/kafka-test-suite) and ask/request me when something is broken or incomplete.

**Comment by luigiberrettini** [comment]
It might be worth giving a try to these:
 - [embedded-kafka](https://github.com/embeddedkafka/embedded-kafka)
 - [kafka-junit](https://github.com/salesforce/kafka-junit)

**Comment by tobiajo** [comment]
Since trying out Testcontainers 6 months back I see no need for this. Unsubscribing.

**Comment by mjsax** [comment]
This seems to be an Apache Kafka issue, and there are corresponding tickets. Please follow up on the Kafka tickets.
