### ISSUE TITLE
Unable to start kafka, since replication factor not set

### ISSUE THREAD

**Issue by nikos** [confluentinc/kafka-streams-examples#272]
With (at least) the 5.3.0 branch the single node kafka instance seems not to be configured properly, but expects the default of three nodes to be available, therefore the logs shows the error messages:

`ERROR [KafkaApi-1] Number of alive brokers '1' does not meet the required replication factor '3' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)`

**Comment by mjsax** [comment]
Seems to be fixed, based on this comment: https://github.com/confluentinc/kafka-streams-examples/pull/273#issuecomment-515608326
