### ISSUE TITLE
Kafka Streams Demo Application: music application REST API bound to localhost

### ISSUE THREAD

**Issue by mtjon** [confluentinc/kafka-streams-examples#277]
# Issue
When following the instructions in `docs/index.rst` using release `5.3.0` a `curl -sXGET http://localhost:7070/kafka-music/instances` from my Docker host returns a 'connection reset by peer' error.
When `docker exec`-ing into the container the same curl works as expected.

# Cause
From what I understand, this issue is caused by the `kafka-music-application`-service's REST API listening to the `localhost`-interface only.

# Resolution
Having the REST API listen to all interfaces, i.e. `0.0.0.0` resolves the issue for me. I have implemented this through the `docker-compose.yml` by changing the `KAFKA_MUSIC_APP_REST_HOST` env variable from `localhost` to `0.0.0.0`.

# Question
Is this behaviour 'as intended'? I'd expect the API to be available from my Docker host.

**Comment by ableegoldman** [comment]
Thanks for the find! You should be able to access IQ results from outside the container -- I'll send in a patch for the affected branches.

**Comment by ableegoldman** [comment]
https://github.com/confluentinc/kafka-streams-examples/pull/278/

**Comment by mtjon** [comment]
Great, glad it was a useful remark. Suppose I can close this, then. Thanks. :)
