### ISSUE TITLE
Sliding Window without join

### ISSUE THREAD

**Issue by bdun1013** [confluentinc/kafka-streams-examples#292]
I have a use case where I would like aggregate records from one topic using a sliding window. It seems that it is only possible to use sliding windows with the [JoinWindows class](https://kafka.apache.org/20/documentation/streams/developer-guide/dsl-api.html#sliding-time-windows).

There is a [StackOverflow question](https://stackoverflow.com/questions/49119379/kafka-kstream-related-message-events-in-sliding-window) that does not have an answer, but there is a suggestion to "implement the windowing logic manually using a transform() step with an attached state."

Is this possible and are there any examples?

**Comment by mjsax** [comment]
Sliding window support for aggregation was added in Apache Kafka 2.7 / Confluent Platform 6.1.

Cf https://issues.apache.org/jira/browse/KAFKA-5636
