### ISSUE TITLE
How to stop kstream app on kafka disconnection

### ISSUE THREAD

**Issue by Josca** [confluentinc/kafka-streams-examples#294]
Hi,
 how to configure Kafka Streams application to shut down after Kafka broker stops? I tried different properties but without success. Kafka Streams app is still trying to reconnect.
Thanks, Josef

**Comment by mjsax** [comment]
That is not possible atm. Maybe you could do it after https://issues.apache.org/jira/browse/KAFKA-6520 is resolved.

**Comment by Josca** [comment]
@mjsax thanks, it's a little bad news for me, but at least I know that it's useless to trying to configure my app this way.
