### ISSUE TITLE
when  i try  to delete  specific  topic  it  crash the  Kafka  and  suddenly stopped  why ? ?

### ISSUE THREAD

**Issue by zeinabkamel** [confluentinc/kafka-streams-examples#323]
![Select Command Prompt 3_5_2020 4_15_10 PM](https://user-images.githubusercontent.com/47484937/75990258-4d9b9480-5efd-11ea-9abe-3569e4797dc1.png)

**Comment by zeinabkamel** [comment]
@travisjeffery

**Comment by mjsax** [comment]
Seems to be unrelated to this example repo. Please file a ticket for Apache Kafka: https://issues.apache.org/jira/projects/KAFKA/issues
