### ISSUE TITLE
Javadocs for some classes can't be downloaded

### ISSUE THREAD

**Issue by keltik85** [confluentinc/kafka-streams-examples#325]
I am on the *trunk* branch. My IDE can't find the Javadocs for the `kafka.admin.AdminUtils` class with the error:
```
Sources not found for: org.apache.kafka:kafka_2.11:2.0.0-cp1
```

Also ` org.I0Itec.zkclient.ZkClient`:
```
Sources not found for: com.101tec:zkclient:0.9
```

And the missing javadocs and source for Avro hurt the most, e.g. `io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde` (becasue they are such an essential part of building a resilient code base):

```
Sources not found for: io.confluent:kafka-streams-avro-serde:5.0.0
```

Are the sources and the javadoc left out deliberately or is this an error?

**Comment by OneCricketeer** [comment]
If you want Javadoc for Kafka, don't use `-cp1` dependency

If you want for ZKClient, post your issue there - https://github.com/sgroschupf/zkclient

For Schema Registy, move this issue there - https://github.com/confluentinc/schema-registry/issues/1428
