### ISSUE TITLE
Cast error

### ISSUE THREAD

**Issue by antonjos** [confluentinc/kafka-streams-examples#326]
Class: SumLambdaExample
line: final KStream<Void, Integer> input = builder.stream(NUMBERS_TOPIC);

this declaration makes application crash due to a ClassCastException when SumLambdaExampleDriver sends data. It tries to convert Integer (the type of the key) to type Void.

**Comment by mjsax** [comment]
PR: https://github.com/confluentinc/kafka-streams-examples/pull/403
