### ISSUE TITLE
pull access denied for placeholder/confluentinc/cp-base-new, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by larryzhu2018** [confluentinc/kafka-streams-examples#328]
I ran into the following error when build docker image
  
mvn -X clean package -Pdocker -DskipTests 

errors:
pull access denied for placeholder/confluentinc/cp-base-new, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by andysv7** [comment]
The error is due to the name of the pull is misspelled or does not exist, check the name "placeholder/confluentinc/cp-base-new" if it exists or is spelled correctly, put the name in google and put the docker hub aside.

**Comment by marcuslinke** [comment]
For me the following works with the 6.0.0-post branch

`mvn clean package -Pdocker -DskipTests -Ddocker.registry= -Ddocker.tag=6.0.0`

**Comment by psp316r** [comment]
Have the same issue, but the following command didn't solve my issue 

```shell
mvn clean package -Pdocker -DskipTests -Ddocker.registry= -Ddocker.tag=6.0.0
```
is there any other way to solve this ?
