### ISSUE TITLE
Inner join by key where key is GenericRecord

### ISSUE THREAD

**Issue by victorchicu** [confluentinc/kafka-streams-examples#33]
Hi everyone,
Is it possible to join records where both records from topic A and B for instance has a key as GenericRecord type?
It's clear for primitive types, Kafka doing the join and trigger the ValueJoiner but if my topics has key as GenericType nothing happens.
Of course I can apply selectKey to select some concrete field from GenericRecord but in my case I need to do some boolean expression evaluating before to join records.
Maybe some how I can override the equals method or it is wrong way?
I still don't understand how Kafka join 2 records from both topics, tried to debug and I didn't found the place where kafka doing something like keyFromttopic1 == keyFromTopic2 e.t.c.

**Comment by loopnotzero** [comment]
KStream-KStream

**Comment by mjsax** [comment]
The join happens here: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamKStreamJoin.java#L88-L100

For a join, there is a windowed store for each input side that buffers all incoming records (this happens in an upstream processor: https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamJoinWindow.java#L64).

Additionally, each input record is used to so a lookup in the other store to find matching keys. The store lookup is basically the evaluation of the `==` predicate on the key plus the timestamp evaluation (cf. the `otherWindow.fetch(key, timeFrom, timeTo)` operation).

Before the join is done, Kafka Streams ensures that both input topics have the same number of partitions and that data is partitioned on the key. Thus, topic1-partition0 and topic2-partition-0 will contain the same keys and can be processed within a single thread.

Hope this helps.
