### ISSUE TITLE
Replace io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig with AbstractKafkaSchemaSerDeConfig

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-streams-examples#336]
Warning during compile:

```
io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig in io.confluent.kafka.serializers has been deprecated
```

Resolve: use new class: https://github.com/confluentinc/schema-registry/blob/5.5.0-post/schema-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaSchemaSerDeConfig.java

**Comment by rspurgeon** [comment]
I'm addressing this as part of some changes for running the microservices against cloud

**Comment by ybyzek** [comment]
@rspurgeon is this GH issue resolved by https://github.com/confluentinc/kafka-streams-examples/pull/346/files ?  If so, can you please mark Closed?

**Comment by rspurgeon** [comment]
@ybyzek I wasn't able to get this resolved across the entire repo, so I left this issue open.

**Comment by ybyzek** [comment]
@rspurgeon Are you planning to resolve this across the entire repo?  If not, you can unassign yourself from the issue.

**Comment by saurabh-slacklife** [comment]
@ybyzek I don't mind picking this up and I can see deprecated warning at 34 different places - for entire repo. Let me know if I can and also the version to push to(6.0.1-post?)

Thanks.

**Comment by ybyzek** [comment]
@saurabh-slacklife -- that would be 🆒 , thanks!  At this time, `6.1.1-post` is the latest, so I would recommend working off that branch.

**Comment by saurabh-slacklife** [comment]
> @saurabh-slacklife -- that would be 🆒 , thanks!  At this time, `6.1.1-post` is the latest, so I would recommend working off that branch.

Acknowledged.

**Comment by saurabh-slacklife** [comment]
There are certain more Java related deprecated warnings:

1. Usage of "**schema.registry.basic.auth.user.info**". From Confluent 5.0 "schema.registry" was dropped and per the Compatibility Matrix, the current code branch is compatible with Confluent 5.4, therefore I believe this should also be updated.
2. Certain state store methods in KafkaStreams.

Not sure if you would like these to be tracked and fixed under this bug.

Thanks

**Comment by ybyzek** [comment]
@saurabh-slacklife IMO this is up to you to define scope, either:

1. Address the one specific warning mentioned in the title/description
2. Remove ALL related warnings (in which case, you can update the title/description)

**Comment by saurabh-slacklife** [comment]
@ybyzek Cool, I'll update the scope and make another commit tomorrow morning.

**Comment by mjsax** [comment]
@saurabh-slacklife -- it's also ok we we do multiple smaller PRs -- easier to review and quicker to merge. So maybe just address the simple comment I left on the PR, and do a follow up PR for the other required changes. Thanks.

**Comment by saurabh-slacklife** [comment]
@mjsax I'm also in favour of multiple PRs. Just made the commit with your review comments.

**Comment by saurabh-slacklife** [comment]
@ybyzek I don't have the edit permission to update the title/description. If you can help to update the scope.

@mjsax For review. Just pushed another PR for the remaining changes.
Thanks.

**Comment by mjsax** [comment]
What is the status of this ticket?

**Comment by saurabh-slacklife** [comment]
This can be closed now, the # mentioned in description and in comments are were handled. I don't have permission to make any modifications.

**Comment by mjsax** [comment]
Thanks for your help to fix this issue @saurabh-slacklife!
