### ISSUE TITLE
Can not find class under package io.confluent.examples.streams.avro

### ISSUE THREAD

**Issue by iXingo** [confluentinc/kafka-streams-examples#337]
Can not find class `io.confluent.examples.streams.avro.microservices.OrderState` and  `io.confluent.examples.streams.avro.microservices.Product`

![image](https://user-images.githubusercontent.com/3634305/83382541-e0bd6b00-a415-11ea-8c91-2ad1692f75fe.png)

**Comment by mjsax** [comment]
Did you read the README: https://github.com/confluentinc/kafka-streams-examples#using-intellij-or-eclipse

**Comment by iXingo** [comment]
Thanks.
