### ISSUE TITLE
Global store does not work in Processor API

### ISSUE THREAD

**Issue by hitenny** [confluentinc/kafka-streams-examples#351]
I have the following topology. 

    Topology topology = new Topology();
            
    //WS connection processor
    topology.addSource(SOURCE1, new StringDeserializer(), new WebSocketConnectionEventDeserializer(), "topic1")
        .addProcessor(PROCESSOR1, Processor1::new, SOURCE1)
        .addStateStore(sessionStoreBuilder, PROCESSOR1)
        .addSink(WS_STATUS_SINK, "sinktopic", stringSerializer, stringSerializer, PROCESSOR1)

    //Service discovery
        .addGlobalStore(nodeTopicDiscoveryStoreBuilder, SOURCE3, new StringDeserializer(),
                    new ServiceDiscoveryEventDeserializer(), "compacttopic", GLOBALSTOREPROCESSOR,
                    GlobalStateStoreBuilder::new)

    //WS session routing
        .addSource(SOURCE2, new StringDeserializer(), new StringDeserializer(),
                    "topic2")
        .addProcessor(PROCESSOR2, Processor2::new,
                    SOURCE2)
        .addStateStore(userConnectedNodesStoreBuilder, PROCESSOR2, PROCESSOR1);

    streams = new KafkaStreams(topology, kafkaStreamProperties);  

While running the application, I get the following error

`Consumer clientId=ws-stream-processor-6115be26-b6e0-49d7-9c47-d9215bfcfea8-StreamThread-1-consumer, groupId=ws-stream-processor] The following subscribed topics are not assigned to any members: [compacttopic]`

**Comment by mjsax** [comment]
Sounds like a bug in Kafka Streams. I filed https://issues.apache.org/jira/browse/KAFKA-13203

What version of Kafka Streams are you using? Could you add this information to the ticket?

Closing this issue, as it's not related to the examples repo. Thanks for reporting!
