### ISSUE TITLE
Example of Streams-Table join with retry disappeared

### ISSUE THREAD

**Issue by sarwarbhuiyan** [confluentinc/kafka-streams-examples#377]
There was an example of how to deal with late arriving data in a table in a stream-table join here: https://github.com/confluentinc/kafka-streams-examples/blob/5.2.3-post/src/test/ja[…]uent/examples/streams/CustomStreamTableJoinIntegrationTest.java  However, something must have gone wrong in code merging because later versions of the code don’t have the logic to handle the data arriving in the Table side: See https://github.com/confluentinc/kafka-streams-examples/blob/6.0.1-post/src/test/ja[…]uent/examples/streams/CustomStreamTableJoinIntegrationTest.java

**Comment by mjsax** [comment]
Seems it was changes on purpose, but I am not 100% sure why: https://github.com/confluentinc/kafka-streams-examples/pull/287

\cc @guozhangwang @ableegoldman @bbejeck

**Comment by huangzhongming** [comment]
Seems the latest code is using max.task.idle.ms and removed the transformer logic, but also changed the expectedOutputRecords which changed the original behavior

![image](https://user-images.githubusercontent.com/2234555/141113582-aa666ed3-1e3e-4bd4-82de-a1679a177aab.png)
