### ISSUE TITLE
WordCountInteractiveQueriesRestService does not close its state store iterators

### ISSUE THREAD

**Issue by rooeyhooey** [confluentinc/kafka-streams-examples#39]
We discovered this while trying to follow this particular example for ways to interactively query the state store. The iterator is not being closed and the memory footprint of the application would grow while the REST api is being queried.

**Comment by mjsax** [comment]
It's the users responsibility to close iterators returned from IQ calls. This is documented in the corresponding JavaDocs IIRC (note, that it was not documented in some older releases unfortunately).
