### ISSUE TITLE
How to create Kafka Server with org.apache.kafka:kafka_2.13:test:2.7.1

### ISSUE THREAD

**Issue by abstract-thinking** [confluentinc/kafka-streams-examples#409]
Hi,

I checked out your project and it works like a charm. I recognized that you used as the Kafka server  org.apache.kafka:kafka_2.13:test:7.0.0-ccs.

I copied the integration test code SpecificAvroIntegrationTest to my project and some stuff like zookeeper package and kafka package until I got it to compile.

One compile error I had to fix: kafka.advertisedListeners().head().

But I can not start the Kafka server. It looks that the connection does not work with Zookeeper.

```
15:47:04.334 [main] DEBUG com.example.demostream.kafka.EmbeddedSingleNodeKafkaCluster - ZooKeeper instance is running at 127.0.0.1:35479
15:47:04.833 [main-SendThread(127.0.0.1:35479)] DEBUG org.apache.zookeeper.SaslServerPrincipal - Canonicalized address to localhost
15:47:04.834 [main-SendThread(127.0.0.1:35479)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost/127.0.0.1:35479.
15:47:04.835 [main-SendThread(127.0.0.1:35479)] INFO org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
15:47:04.844 [main-SendThread(127.0.0.1:35479)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for sever localhost/127.0.0.1:35479, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
```

The only think which I recognizing is that my app uses org.apache.kafka:kafka_2.13:test:2.7.1. This dependency comes with org.springframework.kafka:spring-kafka-test:jar:2.7.8:test into the Maven project.

Further I recognizing this:
```
15:47:02.328 [Thread-0] INFO org.apache.zookeeper.server.ZooKeeperServerMain - Starting server
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir
```

I'm right that the Integration test runs only with your Kafka version? org.apache.kafka:kafka_2.13:test:7.0.0-ccs. Or could it be something else?

Thanks,
Markus

**Comment by OneCricketeer** [comment]
> `NoClassDefFoundError: com/codahale/metrics/Reservoir`

To fix this, you'll need to ensure that metrics package is added to your test scope. It's not dependent upon the Kafka version that is used, no. 

Alternatively, you can use TestContainers rather than copy around the embedded Kafka code. Or, Spring Kafka already has an embedded broker on its own that you should use, instead.
