### ISSUE TITLE
Do we have example on Kafka Stream Processor API to handle Smart routing case

### ISSUE THREAD

**Issue by xzhan** [confluentinc/kafka-streams-examples#412]
Hi team,

here is my requirement as below flow describe , we need to smart routing source (deploy on AWS) to target (internal DC)
Problem define:
We have different Kafka clusters , one is building on AWS , one is on our internal DC.
here is our call flow diagram, Wx internal DC consume service can only connect internal DC Kafka , we want to build one routing service base on some static rule to forward message from AWS Cluster kafka to Internal DC Kafka

Example:
AWS cluster Kafka send message bring Header (Key :domain, Value: domain001 )
Router service parse Header base on domain001 query DC mapping then send to target Internal DC Kafka

can our Kafka-Stream Processor API can handle it well ?

**Comment by mjsax** [comment]
Kafka Streams can only connect to a single cluster. Thus, the only pattern you could apply is to create additional topics in the source cluster and route the records into those "routing topics". Using a replication tool (like Confluent Replicator or MirrorMaker or others), you can copy the data from the "routing topics" to the target cluster.
