### ISSUE TITLE
Is The class of DeserializationExceptionHandler support construct with parameters

### ISSUE THREAD

**Issue by egbertbox** [confluentinc/kafka-streams-examples#422]
Hi, team,
   We want to customize DeserializationExceptionHandler.class which get instance with parameters.
like this.
public DeserializationExceptionHandlerNew(Redisclient redisclient)

Is it possible?

**Comment by mjsax** [comment]
Well, not via the constructor.

`DeserializationExceptionHandler` implements `Configurable` interface, so you can actually implement the `configure(Map<String, ?> configs)` method to create a `Redisclient` and use it later.
