### ISSUE TITLE
Regarding Sum example

### ISSUE THREAD

**Issue by javaHelper** [confluentinc/kafka-streams-examples#438]
I'm sending data like below'

```sh
kafka-console-producer --bootstrap-server localhost:9092 --topic numbers-topic
>1223
>1223 
>
```

I wonder, why I am getting below response?

```sh
kafka-console-consumer --topic sum-of-odd-numbers-topic --from-beginning --bootstrap-server localhost:9092 --property value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
1650746470
```

Also, I'm not clear on how to send data to topic as instructions are not clear to me

**Comment by OneCricketeer** [comment]
> not clear on how to send data to topic

You're already using `kafka-console-producer`. 

But this accepts strings, not numbers. You'll need to add `--property value.serializer` for IntegerSerializer, similar to how you did for the consumer
