### ISSUE TITLE
Can't find the package io.confluent.examples.streams.avro in src folder

### ISSUE THREAD

**Issue by zzhorse** [confluentinc/kafka-streams-examples#440]
Please can tell me where to find the source of package io.confluent.examples.streams.avro? It cause compile error in io.confluent.examples.streams.microservices.OrderService.java etc.

**Comment by OneCricketeer** [comment]
It's a generated class. The [resources](https://github.com/confluentinc/kafka-streams-examples/tree/7.1.1-post/src/main/resources/avro/io/confluent/examples/streams) is where you'd find it. 

Are you using `mvn compile` before running the code?
