### ISSUE TITLE
How to suppress window using wall clock time instead of event time in Kafka streams?

### ISSUE THREAD

**Issue by soutong** [confluentinc/kafka-streams-examples#441]
The suppress will not flush the aggregated record till it encounters the same group-by key!!!，how can i do?

**Comment by mjsax** [comment]
You can't do anything about it (if you are using emit-on-window-close). The purpose of `suppress()` is to ensure to not miss any out-of-order data so it needs to wait...

I am closing this question, but feel free to follow up.
