### ISSUE TITLE
docker-compose up fails! Missing docker image for 4.0.0

### ISSUE THREAD

**Issue by netrounds-joakim** [confluentinc/kafka-streams-examples#66]
# v4.0.0 (FAILS)
I'm trying to follow the guide to running the demo application:
https://docs.confluent.io/current/streams/kafka-streams-examples/docs/index.html

Running the services as in the example:
```
docker-compose up -d
...
Digest: sha256:164ea53ad8e42c4cc5ab8ae7269d1f4b455e333c2ba2971d8279e3840930b64f
Status: Downloaded newer image for confluentinc/cp-schema-registry:latest
Pulling kafka-music-data-generator (confluentinc/kafka-streams-examples:4.0.0-SNAPSHOT)...
ERROR: manifest for confluentinc/kafka-streams-examples:4.0.0-SNAPSHOT not found
```

Looking at your docker repository, there is no `4.0.0-SNAPSHOT` tag.
https://hub.docker.com/r/confluentinc/cp-kafka-streams-examples/tags/

This means checking out this repository as is will not work.

Also attempting to build this image myself locally using the `Dockerfile` in the repo is non-trivial, since it uses a bunch of `ARG` and `ENV` statements I have no idea what I'm supposed to set them to:
https://github.com/confluentinc/kafka-streams-examples/blob/aee33b64c1d2dc9cd0ce7b27b6f7440a2bfd19e9/Dockerfile#L26-L47

And I could find no instructions on this.

# v3.3.1 (FAILS)

I checkout out **v3.3.1** and that fails as well:
```
Pulling kafka-music-data-generator (confluentinc/kafka-streams-examples:3.3.1-SNAPSHOT)...
ERROR: manifest for confluentinc/kafka-streams-examples:3.3.1-SNAPSHOT not found
```

# Older versions

The latest version on docker hub is **v3.2.2**. And this is the tags found in this repo:
```
$ git tag
v3.3.0-1
v3.3.1
v3.3.1-rc0
v3.3.1-rc2
v3.3.1-rc3
v3.3.1-rc4
v3.3.1-rc5
v4.0.0
v4.0.0-rc0
v4.0.0-rc1
v4.0.0-rc2
v4.0.0-rc3
```

So there is no way to run this "out of the box"

**Comment by bbejeck** [comment]
@netrounds-joakim sorry about that.  We've just pushed a fix, can you pull and try again?

Thanks!

**Comment by netrounds-joakim** [comment]
@bbejeck works now, thank you

**Comment by 87abhii** [comment]
PXT7972TA13MAC:kafka-streams-examples user$ docker-compose up
Pulling zookeeper (confluentinc/cp-zookeeper:5.4.0-SNAPSHOT)...
ERROR: manifest for confluentinc/cp-zookeeper:5.4.0-SNAPSHOT not found
PXT7972TA13MAC:kafka-streams-examples user$
